runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:application

runtime_config:
  python_version: 3

manual_scaling:
  instances: 1 ## parrallaly (to deal with multiple requests) many applications will run if given more
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
